name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Update based on your Jekyll requirements
          bundler-cache: true

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          bundle install
      # Step 4: Build the Jekyll site
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --source . --destination _site
      # Step 5: Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          
      - name: Deploy to _sites folder
        run: |
          git config --local user.name "vishnugt"
          git add ./_site
          git commit -m "Updating the _site via Github Actions"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
